### ISSUE TITLE
Error: Please add a @Pipe/@Directive/@Component annotation

### ISSUE THREAD

**Issue by itprogrammer2** [KostyaTretyak/ng-contenteditable#3]
Hi, 

My name is Rafael. Need help with my Angular 4 application.

ng-contenteditable is working just fine when I am running my app using `ng serve` but when I try to run `ng build --prod`, I get this error `Error: Please add a @Pipe/@Directive/@Component annotation`

What am I doing wrong?

Here is the complete error from my terminal:

ERROR in Error: Unexpected value 'ContenteditableDirective in /home/rafael/node/c/node_modules/ng-contenteditable/dist/index.d.ts' declared by the module 'AppModule in /home/rafael/node/c/src/app/app.module.ts'. Please add a @Pipe/@Directive/@Component annotation.
    at syntaxError (/home/rafael/node/c/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at /home/rafael/node/c/node_modules/@angular/compiler/bundles/compiler.umd.js:15630:40
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (/home/rafael/node/c/node_modules/@angular/compiler/bundles/compiler.umd.js:15612:54)
    at addNgModule (/home/rafael/node/c/node_modules/@angular/compiler/bundles/compiler.umd.js:24408:58)
    at /home/rafael/node/c/node_modules/@angular/compiler/bundles/compiler.umd.js:24419:14
    at Array.forEach (<anonymous>)
    at _createNgModules (/home/rafael/node/c/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:26)
    at analyzeNgModules (/home/rafael/node/c/node_modules/@angular/compiler/bundles/compiler.umd.js:24293:14)
    at analyzeAndValidateNgModules (/home/rafael/node/c/node_modules/@angular/compiler/bundles/compiler.umd.js:24303:35)
    at AotCompiler.analyzeModulesAsync (/home/rafael/node/c/node_modules/@angular/compiler/bundles/compiler.umd.js:23937:46)
    at CodeGenerator.codegen (/home/rafael/node/c/node_modules/@angular/compiler-cli/src/codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (/home/rafael/node/c/node_modules/@angular/compiler-cli/src/ngtools_api.js:73:30)
    at _donePromise.Promise.resolve.then (/home/rafael/node/c/node_modules/@ngtools/webpack/src/plugin.js:386:44)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by itprogrammer2** [comment]
I noticed the required `@angular/core` and `@angular/forms` are version 4.4.4. I previously had 4.4.3 but after upgrading to 4.4.6 (upgrading to 4.4.4 jumps to 4.4.6), I am getting the same error during `ng build --prod`

**Comment by KostyaTretyak** [comment]
Sorry, but your question does not related to `ng-contenteditable`

**Comment by KostyaTretyak** [comment]
@itprogrammer2, I'm very sorry about lock this issue, the problem really exists. I will try to solve it now in https://github.com/KostyaTretyak/ng-contenteditable/issues/5.
